package Numbers;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

import java.util.Scanner;

public class Code2 {
    public static void main(String[] args) {

        int prev = 1;
        int curr = 2;

        int sum = 0;

        int limit;

        Scanner scan = new Scanner(System.in);
        System.out.println("Enter the number");
        limit = scan.nextInt();

        while (prev <= limit) {
            if (prev % 2 == 0) {
                sum += prev;
            }

            // adding prev and curr values
            int next = prev + curr;

            // storing current variable value as a previous value into prev variable
            prev = curr;

            // storing next value into curr variable
            curr = next;
        }

        // print the result
        System.out.println("Sum of even Fibonacci numbers up to " + limit + ": " + sum);

        scan.close();
    }
}
